export const ERROR_CODES = {
  // 일반적인 오류
  GENERAL: {
    INTERNAL_SERVER_ERROR: 1000,
    INVALID_PARAMETER: 1001,
    UNAUTHORIZED: 1002,
    FORBIDDEN: 1003,
    NOT_FOUND: 1004,
    DATABASE_ERROR: 1005,
  },

  // 유효성 검사 관련 오류 (2xxx)
  VALIDATION: {
    VALIDATION_FAILED: 2000,
    MISSING_FIELDS: 2001,
    MISSING_TOKEN: 2002,
  },

  // 인증 관련 오류 (3xxx)
  AUTH: {
    AUTHENTICATION_FAILED: 3000,
    INVALID_CREDENTIALS: 3001,
    TOKEN_EXPIRED: 3002,
    INVALID_TOKEN: 3003,
    USER_NOT_FOUND: 3004,
    USER_ALREADY_EXISTS: 3005,
  },

  // 아이템 관련 오류 (4xxx)
  ITEM: {
    CREATION_FAILED: 4000,
    NOT_FOUND: 4001,
    UPDATE_FAILED: 4002,
    DELETION_FAILED: 4003,
    NOT_OWNER: 4004,
    NOTHING_TO_UPDATE: 4005,
  },
};

// HTTP 상태 코드와 매핑되는 에러 코드 (선택적)
export const HTTP_STATUS_ERROR_MAP = {
  400: ERROR_CODES.GENERAL.INVALID_PARAMETER,
  401: ERROR_CODES.GENERAL.UNAUTHORIZED,
  403: ERROR_CODES.GENERAL.FORBIDDEN,
  404: ERROR_CODES.GENERAL.NOT_FOUND,
  500: ERROR_CODES.GENERAL.INTERNAL_SERVER_ERROR,
};
